name: myshop
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  bottom_navy_bar: ^5.5.0
  status_alert: ^0.1.2
  flutter_spinkit: ^4.1.2+1
  animated_text_kit: ^2.2.0
  font_awesome_flutter: ^8.8.1
  timeago: ^2.0.27
  eva_icons_flutter: ^2.0.1
  flutter_signin_button: ^1.1.0
  firebase_core: "0.5.0"
  firebase_auth: "^0.18.0+1"
  cloud_firestore: "^0.14.0+2"
  google_sign_in: "^4.5.1"
  firebase_storage: ^4.0.0
  firebase_analytics: "^6.0.0"
  url_launcher: ^5.5.3
  image_picker: ^0.6.7+7
  image_cropper: ^1.3.1
  shimmer: ^1.1.1
  shared_preferences: '>=0.5.10 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.5"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/icon_background.png"
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts: 
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
